Repository TTTM-Mavericks/smart-tailor-BE, pull requests merged in 2024-08, with the labels that each got.

#154 Update SizeExpertTailoring Entity and Code Related
  src/main/java/com/smart/tailor/entities/SizeExpertTailoring.java
  src/main/java/com/smart/tailor/mapper/SizeExpertTailoringMapper.java
  src/main/java/com/smart/tailor/repository/SizeExpertTailoringRepository.java
  src/main/java/com/smart/tailor/service/ExcelImportService.java
  src/main/java/com/smart/tailor/service/impl/ExcelExportServiceImpl.java
  src/main/java/com/smart/tailor/service/impl/ExcelImportServiceImpl.java
  src/main/java/com/smart/tailor/service/impl/MaterialServiceImpl.java
  src/main/java/com/smart/tailor/service/impl/SizeExpertTailoringServiceImpl.java
  src/main/java/com/smart/tailor/utils/request/SizeExpertTailoringRequest.java
  src/main/java/com/smart/tailor/utils/response/SizeExpertTailoringResponse.java
Labels: function, update, Fix Code

#156 Update Code Calculate Price for Order
  src/main/java/com/smart/tailor/service/DesignDetailService.java
  src/main/java/com/smart/tailor/service/impl/DesignDetailServiceImpl.java
  src/main/java/com/smart/tailor/utils/response/BrandDetailPriceResponse.java
  src/main/java/com/smart/tailor/utils/response/OrderDetailPriceResponse.java
Labels: function, update, Fix Code

#158 [BE0070] order progress management
  src/main/java/com/smart/tailor/constant/APIConstant.java
  src/main/java/com/smart/tailor/constant/MessageConstant.java
  src/main/java/com/smart/tailor/controller/OrderController.java
  src/main/java/com/smart/tailor/entities/OrderStage.java
  src/main/java/com/smart/tailor/mapper/OrderStageMapper.java
  src/main/java/com/smart/tailor/repository/OrderStageRepository.java
  src/main/java/com/smart/tailor/service/OrderService.java
  src/main/java/com/smart/tailor/service/OrderStageService.java
  src/main/java/com/smart/tailor/service/impl/DesignDetailServiceImpl.java
  src/main/java/com/smart/tailor/service/impl/OrderServiceImpl.java
  src/main/java/com/smart/tailor/service/impl/OrderStageServiceImpl.java
  src/main/java/com/smart/tailor/utils/request/OrderStageRequest.java
  src/main/java/com/smart/tailor/utils/response/OrderStageResponse.java
Labels: bug, function, update, Fix Code

#159 [BE0070] create parent stage
  src/main/java/com/smart/tailor/enums/PaymentType.java
  src/main/java/com/smart/tailor/service/impl/OrderServiceImpl.java
Labels: function, update, Fix Code

#160 Feature be0070 order progress management
  src/main/java/com/smart/tailor/service/impl/OrderServiceImpl.java
Labels: function, update

#161 [BE0070] change status order
  src/main/java/com/smart/tailor/service/impl/OrderServiceImpl.java
Labels: update, Fix Code

#162 [BE0070] update sample data
  src/main/java/com/smart/tailor/entities/SampleProductData.java
  src/main/java/com/smart/tailor/mapper/SampleProductDataMapper.java
  src/main/java/com/smart/tailor/repository/SampleProductDataRepository.java
  src/main/java/com/smart/tailor/service/impl/SampleProductDataServiceImpl.java
  src/main/java/com/smart/tailor/utils/request/SampleProductDataRequest.java
Labels: bug, function, update, Fix Code

#163 [BE-0071] Create SQL Script for Material, BrandMaterial, SizeExpertTailoring, BrandLaborQuantity
  src/main/java/com/smart/tailor/SmartTailorBeApplication.java
  src/main/resources/application.properties
  src/main/resources/smartTailorScript.sql
Labels: function

#164 Feature be0070 order progress management
  src/main/java/com/smart/tailor/entities/SampleProductData.java
  src/main/java/com/smart/tailor/mapper/SampleProductDataMapper.java
  src/main/java/com/smart/tailor/repository/SampleProductDataRepository.java
  src/main/java/com/smart/tailor/service/impl/SampleProductDataServiceImpl.java
  src/main/java/com/smart/tailor/utils/request/SampleProductDataRequest.java
  src/main/java/com/smart/tailor/utils/response/SampleProductDataResponse.java
Labels: function, update, Fix Code

#165 Order Time Line by Parent Order ID
  src/main/java/com/smart/tailor/SmartTailorBeApplication.java
  src/main/java/com/smart/tailor/constant/APIConstant.java
  src/main/java/com/smart/tailor/controller/OrderController.java
  src/main/java/com/smart/tailor/enums/OrderStatus.java
  src/main/java/com/smart/tailor/service/OrderService.java
  src/main/java/com/smart/tailor/service/impl/DesignDetailServiceImpl.java
  src/main/java/com/smart/tailor/service/impl/OrderServiceImpl.java
  src/main/java/com/smart/tailor/utils/Utilities.java
  src/main/java/com/smart/tailor/utils/response/BrandDetailPriceResponse.java
  src/main/java/com/smart/tailor/utils/response/OrderDetailPriceResponse.java
  src/main/java/com/smart/tailor/utils/response/OrderTimeLineResponse.java
  src/main/resources/application.properties
  src/main/resources/smartTailorScript.sql
Labels: function

#166 [BE0061] Rating Order and Brand
  src/main/java/com/smart/tailor/entities/Brand.java
  src/main/java/com/smart/tailor/repository/BrandRepository.java
  src/main/java/com/smart/tailor/service/BrandService.java
  src/main/java/com/smart/tailor/service/impl/BrandServiceImpl.java
  src/main/java/com/smart/tailor/service/impl/OrderServiceImpl.java
  src/main/resources/smartTailorScript.sql
Labels: function, update

#168 Feature be0070 order progress management
  src/main/java/com/smart/tailor/constant/APIConstant.java
  src/main/java/com/smart/tailor/controller/SampleProductDataController.java
  src/main/java/com/smart/tailor/service/SampleProductDataService.java
  src/main/java/com/smart/tailor/service/impl/OrderServiceImpl.java
  src/main/java/com/smart/tailor/service/impl/SampleProductDataServiceImpl.java
Labels: bug, function, update, Fix Code

#167 Update Code Register
  src/main/java/com/smart/tailor/service/impl/AuthenticationServiceImpl.java
Labels: update, Fix Code

#169 Feature be0061 rating order
  src/main/java/com/smart/tailor/constant/APIConstant.java
  src/main/java/com/smart/tailor/controller/BrandController.java
  src/main/java/com/smart/tailor/mapper/BrandMapper.java
  src/main/java/com/smart/tailor/service/BrandService.java
  src/main/java/com/smart/tailor/service/impl/BrandServiceImpl.java
  src/main/java/com/smart/tailor/service/impl/OrderServiceImpl.java
  src/main/java/com/smart/tailor/utils/response/BrandResponse.java
Labels: function, update, Fix Code

#170 Update Order Time Line by SubOrderQuantity
  src/main/java/com/smart/tailor/service/impl/DesignDetailServiceImpl.java
  src/main/java/com/smart/tailor/service/impl/OrderServiceImpl.java
Labels: function, update

#171 Feature be0016 crud brand
  src/main/java/com/smart/tailor/constant/APIConstant.java
  src/main/java/com/smart/tailor/constant/MessageConstant.java
  src/main/java/com/smart/tailor/controller/BrandController.java
  src/main/java/com/smart/tailor/entities/Brand.java
  src/main/java/com/smart/tailor/entities/BrandImage.java
  src/main/java/com/smart/tailor/mapper/BrandImageMapper.java
  src/main/java/com/smart/tailor/mapper/BrandMapper.java
  src/main/java/com/smart/tailor/repository/BrandImageRepository.java
  src/main/java/com/smart/tailor/service/BrandImageService.java
  src/main/java/com/smart/tailor/service/BrandService.java
  src/main/java/com/smart/tailor/service/impl/BrandImageServiceImpl.java
  src/main/java/com/smart/tailor/service/impl/BrandServiceImpl.java
  src/main/java/com/smart/tailor/utils/request/BrandImageRequest.java
  src/main/java/com/smart/tailor/utils/request/BrandRequest.java
  src/main/java/com/smart/tailor/utils/response/BrandImageResponse.java
  src/main/java/com/smart/tailor/utils/response/BrandResponse.java
Labels: bug, update, Fix Code

#172 [BE0032] update order response - add brand response
  src/main/java/com/smart/tailor/mapper/OrderMapper.java
  src/main/java/com/smart/tailor/utils/response/OrderResponse.java
Labels: function, update

#173 Update Code Send Mail, Fix Code ScheduleTask DeleteUser, Config Syste…
  src/main/java/com/smart/tailor/constant/FormatConstant.java
  src/main/java/com/smart/tailor/service/ExcelExportService.java
  src/main/java/com/smart/tailor/service/impl/AuthenticationServiceImpl.java
  src/main/java/com/smart/tailor/service/impl/BrandMaterialServiceImpl.java
  src/main/java/com/smart/tailor/service/impl/ExcelExportServiceImpl.java
  src/main/java/com/smart/tailor/service/impl/ScheduleTaskServiceImpl.java
  src/main/resources/application.properties
  src/main/resources/smartTailorScript.sql
  src/main/resources/templates/TemplateChangePassword.html
  src/main/resources/templates/TemplateResetPassword.html
  src/main/resources/templates/TemplateSelectedBrandForSpecificOrder.html
  src/main/resources/templates/TemplateVerifyAccount.html
Labels: function, update, Fix Code

#174 Update Code OrderTimeline and Generate Random String
  src/main/java/com/smart/tailor/SmartTailorBeApplication.java
  src/main/java/com/smart/tailor/mapper/OrderStageMapper.java
  src/main/java/com/smart/tailor/service/impl/OrderServiceImpl.java
  src/main/java/com/smart/tailor/utils/response/OrderStageResponse.java
  src/main/resources/application.properties
Labels: update, Fix Code

#175 Feature be0032 crud order
  src/main/java/com/smart/tailor/constant/APIConstant.java
  src/main/java/com/smart/tailor/controller/OrderController.java
  src/main/java/com/smart/tailor/mapper/OrderMapper.java
  src/main/java/com/smart/tailor/service/OrderService.java
  src/main/java/com/smart/tailor/service/impl/OrderServiceImpl.java
  src/main/java/com/smart/tailor/utils/response/FullOrderResponse.java
Labels: bug, function, update

#177 [BE0016] update brand taxCode
  src/main/java/com/smart/tailor/entities/Brand.java
  src/main/java/com/smart/tailor/service/impl/BrandServiceImpl.java
  src/main/java/com/smart/tailor/utils/request/BrandRequest.java
  src/main/java/com/smart/tailor/utils/response/BrandResponse.java
Labels: function, update

#178 Feature be0038 create payment feature
  src/main/java/com/smart/tailor/mapper/PaymentMapper.java
  src/main/java/com/smart/tailor/service/PayOSService.java
  src/main/java/com/smart/tailor/service/PaymentService.java
  src/main/java/com/smart/tailor/service/ScheduleTaskService.java
  src/main/java/com/smart/tailor/service/impl/OrderServiceImpl.java
  src/main/java/com/smart/tailor/service/impl/PayOSServiceImpl.java
  src/main/java/com/smart/tailor/service/impl/PaymentServiceImpl.java
  src/main/java/com/smart/tailor/service/impl/ScheduleTaskServiceImpl.java
  src/main/resources/application.properties
Labels: bug, function, update, Fix Code

#180 Feature be0032 crud order
  src/main/java/com/smart/tailor/constant/APIConstant.java
  src/main/java/com/smart/tailor/controller/OrderController.java
  src/main/java/com/smart/tailor/service/OrderService.java
  src/main/java/com/smart/tailor/service/impl/OrderServiceImpl.java
Labels: bug, Fix Code

#181 Update Code Report, DesignDetail, SystemProperty for verify token
  src/main/java/com/smart/tailor/service/impl/DesignDetailServiceImpl.java
  src/main/java/com/smart/tailor/service/impl/ReportServiceImpl.java
  src/main/java/com/smart/tailor/service/impl/VerificationTokenServiceImpl.java
  src/main/resources/smartTailorScript.sql
Labels: function, update, Fix Code

#182 Get All Brand Information
  src/main/java/com/smart/tailor/constant/APIConstant.java
  src/main/java/com/smart/tailor/controller/BrandController.java
  src/main/java/com/smart/tailor/service/BrandService.java
  src/main/java/com/smart/tailor/service/impl/BrandServiceImpl.java
Labels: function, update, Fix Code

#183 Update Code Get List Report by UserID
  src/main/java/com/smart/tailor/service/impl/ReportServiceImpl.java
Labels: function, update, Fix Code

#184 Update Code Excel, Set Column Definition for PK
  src/main/java/com/smart/tailor/entities/Brand.java
  src/main/java/com/smart/tailor/entities/BrandExpertTailoringKey.java
  src/main/java/com/smart/tailor/entities/BrandImage.java
  src/main/java/com/smart/tailor/entities/BrandLaborQuantityKey.java
  src/main/java/com/smart/tailor/entities/BrandMaterial.java
  src/main/java/com/smart/tailor/entities/BrandMaterialKey.java
  src/main/java/com/smart/tailor/entities/BrandProperties.java
  src/main/java/com/smart/tailor/entities/Category.java
  src/main/java/com/smart/tailor/entities/Customer.java
  src/main/java/com/smart/tailor/entities/Design.java
  src/main/java/com/smart/tailor/entities/DesignDetail.java
  src/main/java/com/smart/tailor/entities/Employee.java
  src/main/java/com/smart/tailor/entities/ExpertTailoring.java
  src/main/java/com/smart/tailor/entities/ExpertTailoringMaterialKey.java
  src/main/java/com/smart/tailor/entities/ItemMask.java
  src/main/java/com/smart/tailor/entities/LaborQuantity.java
  src/main/java/com/smart/tailor/entities/Material.java
  src/main/java/com/smart/tailor/entities/Notification.java
  src/main/java/com/smart/tailor/entities/Order.java
  src/main/java/com/smart/tailor/entities/OrderStage.java
  src/main/java/com/smart/tailor/entities/PartOfDesign.java
  src/main/java/com/smart/tailor/entities/Payment.java
  src/main/java/com/smart/tailor/entities/Report.java
  src/main/java/com/smart/tailor/entities/ReportImage.java
  src/main/java/com/smart/tailor/entities/Roles.java
  src/main/java/com/smart/tailor/entities/SampleProductData.java
  src/main/java/com/smart/tailor/entities/Size.java
  src/main/java/com/smart/tailor/entities/SizeExpertTailoringKey.java
  src/main/java/com/smart/tailor/entities/SystemImage.java
  src/main/java/com/smart/tailor/entities/SystemProperties.java
  src/main/java/com/smart/tailor/entities/Task.java
  src/main/java/com/smart/tailor/entities/Token.java
  src/main/java/com/smart/tailor/entities/User.java
  src/main/java/com/smart/tailor/entities/UsingNotification.java
  src/main/java/com/smart/tailor/entities/VerificationToken.java
  src/main/java/com/smart/tailor/repository/BrandMaterialRepository.java
  src/main/java/com/smart/tailor/repository/MaterialRepository.java
  src/main/java/com/smart/tailor/service/impl/BrandMaterialServiceImpl.java
  src/main/java/com/smart/tailor/service/impl/ExcelExportServiceImpl.java
  src/main/java/com/smart/tailor/service/impl/MaterialServiceImpl.java
  src/main/java/com/smart/tailor/service/impl/UserServiceImpl.java
  src/main/java/com/smart/tailor/utils/request/BrandMaterialRequest.java
  src/main/java/com/smart/tailor/utils/request/MaterialRequest.java
  src/main/java/com/smart/tailor/utils/response/BrandMaterialResponse.java
  src/main/java/com/smart/tailor/utils/response/MaterialResponse.java
  src/main/resources/application.properties
  src/main/resources/smartTailorScript.sql
Labels: function, update, Fix Code

#185 Feature be0072 flow cancel order
  src/main/java/com/smart/tailor/controller/SampleProductDataController.java
  src/main/java/com/smart/tailor/enums/PaymentType.java
  src/main/java/com/smart/tailor/mapper/PaymentMapper.java
  src/main/java/com/smart/tailor/service/OrderService.java
  src/main/java/com/smart/tailor/service/PayOSService.java
  src/main/java/com/smart/tailor/service/impl/OrderServiceImpl.java
  src/main/java/com/smart/tailor/service/impl/PayOSServiceImpl.java
  src/main/java/com/smart/tailor/service/impl/PaymentServiceImpl.java
  src/main/java/com/smart/tailor/service/impl/ScheduleTaskServiceImpl.java
  src/main/resources/application.properties
Labels: bug, function, update, Fix Code

#186 Feature be0069 calculate shipping price for each order
  src/main/java/com/smart/tailor/constant/APIConstant.java
  src/main/java/com/smart/tailor/controller/OrderController.java
  src/main/java/com/smart/tailor/controller/VietQRController.java
  src/main/java/com/smart/tailor/entities/Order.java
  src/main/java/com/smart/tailor/mapper/OrderMapper.java
  src/main/java/com/smart/tailor/repository/OrderRepository.java
  src/main/java/com/smart/tailor/service/GHTKShippingService.java
  src/main/java/com/smart/tailor/service/OrderService.java
  src/main/java/com/smart/tailor/service/ScheduleTaskService.java
  src/main/java/com/smart/tailor/service/VietQRSerivce.java
  src/main/java/com/smart/tailor/service/impl/DesignDetailServiceImpl.java
  src/main/java/com/smart/tailor/service/impl/GHTKShippingServiceImpl.java
  src/main/java/com/smart/tailor/service/impl/OrderServiceImpl.java
  src/main/java/com/smart/tailor/service/impl/ScheduleTaskServiceImpl.java
  src/main/java/com/smart/tailor/service/impl/VietQRServiceImpl.java
  src/main/java/com/smart/tailor/utils/request/OrderShippingRequest.java
  src/main/java/com/smart/tailor/utils/response/DataResponse.java
  src/main/java/com/smart/tailor/utils/response/FeeResponse.java
  src/main/java/com/smart/tailor/utils/response/FullOrderResponse.java
  src/main/java/com/smart/tailor/utils/response/OrderCustomResponse.java
  src/main/java/com/smart/tailor/utils/response/OrderDetailPriceResponse.java
  src/main/java/com/smart/tailor/utils/response/OrderDetailShippingResponse.java
  src/main/java/com/smart/tailor/utils/response/OrderResponse.java
  src/main/java/com/smart/tailor/utils/response/OrderShippingResponse.java
  src/main/java/com/smart/tailor/utils/response/VietQRResponse.java
  src/main/resources/application.properties
  src/main/resources/smartTailorScript.sql
Labels: function, update, Fix Code

#187 Get All Report By Parent Order ID
  src/main/java/com/smart/tailor/constant/APIConstant.java
  src/main/java/com/smart/tailor/constant/MessageConstant.java
  src/main/java/com/smart/tailor/controller/ReportController.java
  src/main/java/com/smart/tailor/service/ReportService.java
  src/main/java/com/smart/tailor/service/impl/ReportServiceImpl.java
Labels: function, update

#188 [BE0072] update bug payment infor
  src/main/java/com/smart/tailor/service/impl/ScheduleTaskServiceImpl.java
Labels: bug, update, Fix Code

#189 Update Code CreateDate, LastModifiedDate and Script Material, BrandMa…
  src/main/java/com/smart/tailor/config/RestAccessDenyEntryPoint.java
  src/main/java/com/smart/tailor/config/RestUnauthorizedEntryPoint.java
  src/main/java/com/smart/tailor/constant/FormatConstant.java
  src/main/java/com/smart/tailor/mapper/BrandLaborQuantityMapper.java
  src/main/java/com/smart/tailor/mapper/BrandMapper.java
  src/main/java/com/smart/tailor/mapper/BrandMaterialMapper.java
  src/main/java/com/smart/tailor/mapper/CategoryMapper.java
  src/main/java/com/smart/tailor/mapper/DesignDetailMapper.java
  src/main/java/com/smart/tailor/mapper/DesignMapper.java
  src/main/java/com/smart/tailor/mapper/ExpertTailoringMapper.java
  src/main/java/com/smart/tailor/mapper/ExpertTailoringMaterialMapper.java
  src/main/java/com/smart/tailor/mapper/ItemMaskMapper.java
  src/main/java/com/smart/tailor/mapper/LaborQuantityMapper.java
  src/main/java/com/smart/tailor/mapper/MaterialMapper.java
  src/main/java/com/smart/tailor/mapper/OrderMapper.java
  src/main/java/com/smart/tailor/mapper/OrderStageMapper.java
  src/main/java/com/smart/tailor/mapper/PartOfDesignMapper.java
  src/main/java/com/smart/tailor/mapper/ReportImageMapper.java
  src/main/java/com/smart/tailor/mapper/ReportMapper.java
  src/main/java/com/smart/tailor/mapper/SampleProductDataMapper.java
  src/main/java/com/smart/tailor/mapper/SizeExpertTailoringMapper.java
  src/main/java/com/smart/tailor/mapper/SizeMapper.java
  src/main/java/com/smart/tailor/mapper/UserMapper.java
  src/main/java/com/smart/tailor/service/impl/DesignDetailServiceImpl.java
  src/main/java/com/smart/tailor/service/impl/ExcelExportServiceImpl.java
  src/main/java/com/smart/tailor/service/impl/OrderServiceImpl.java
  src/main/java/com/smart/tailor/service/impl/ReportServiceImpl.java
  src/main/java/com/smart/tailor/utils/Utilities.java
  src/main/java/com/smart/tailor/utils/response/FullOrderResponse.java
  src/main/java/com/smart/tailor/utils/response/OrderCustomResponse.java
  src/main/java/com/smart/tailor/utils/response/OrderResponse.java
  src/main/resources/smartTailorScript.sql
Labels: update, Fix Code

#190 [BE0072] add rejected and preparing status for order
  src/main/java/com/smart/tailor/enums/OrderStatus.java
  src/main/java/com/smart/tailor/service/impl/OrderServiceImpl.java
  src/main/java/com/smart/tailor/service/impl/PaymentServiceImpl.java
Labels: update, Fix Code

#191 Feature be0073 notification feature
  src/main/java/com/smart/tailor/config/DataHandler.java
  src/main/java/com/smart/tailor/config/WebSocketConfig.java
  src/main/java/com/smart/tailor/constant/APIConstant.java
  src/main/java/com/smart/tailor/constant/MessageConstant.java
  src/main/java/com/smart/tailor/controller/NotificationController.java
  src/main/java/com/smart/tailor/controller/NotificationHandler.java
  src/main/java/com/smart/tailor/mapper/NotificationMapper.java
  src/main/java/com/smart/tailor/service/NotificationService.java
  src/main/java/com/smart/tailor/service/impl/NotificationServiceImpl.java
  src/main/java/com/smart/tailor/utils/response/NotificationResponse.java
Labels: function, update, Fix Code

#192 Round Price to Nearest Thousand for ParentOrder, SubOrder, Customer, Brand at Each Stage
  src/main/java/com/smart/tailor/SmartTailorBeApplication.java
  src/main/java/com/smart/tailor/service/impl/DesignDetailServiceImpl.java
  src/main/java/com/smart/tailor/utils/Utilities.java
  src/main/java/com/smart/tailor/utils/response/OrderDetailPriceResponse.java
Labels: function, update, Fix Code

#193 [BE0073] update null pointer error
  src/main/java/com/smart/tailor/service/impl/NotificationServiceImpl.java
Labels: bug, update, Fix Code

#195 Feature be0075 fix design conflict and null pointer transactions
  src/main/java/com/smart/tailor/controller/SampleProductDataController.java
  src/main/java/com/smart/tailor/enums/OrderStatus.java
  src/main/java/com/smart/tailor/mapper/OrderMapper.java
  src/main/java/com/smart/tailor/service/DesignService.java
  src/main/java/com/smart/tailor/service/OrderService.java
  src/main/java/com/smart/tailor/service/PartOfDesignService.java
  src/main/java/com/smart/tailor/service/impl/DesignDetailServiceImpl.java
  src/main/java/com/smart/tailor/service/impl/DesignServiceImpl.java
  src/main/java/com/smart/tailor/service/impl/OrderServiceImpl.java
  src/main/java/com/smart/tailor/service/impl/PartOfDesignServiceImpl.java
  src/main/java/com/smart/tailor/service/impl/ScheduleTaskServiceImpl.java
  src/main/java/com/smart/tailor/utils/response/FullOrderResponse.java
  src/main/java/com/smart/tailor/utils/response/OrderCustomResponse.java
  src/main/java/com/smart/tailor/utils/response/OrderResponse.java
Labels: bug, update, Fix Code

#194 Config some Constraint about Report
  src/main/java/com/smart/tailor/repository/OrderRepository.java
  src/main/java/com/smart/tailor/service/OrderService.java
  src/main/java/com/smart/tailor/service/impl/OrderServiceImpl.java
  src/main/java/com/smart/tailor/service/impl/ReportServiceImpl.java
Labels: function, update, Fix Code

#196 Update Order Time Line for Customer base on Specific Quantity
  src/main/java/com/smart/tailor/service/impl/OrderServiceImpl.java
Labels: function, update, Fix Code

#197 Feature be0075 fix design conflict and null pointer transactions
  src/main/java/com/smart/tailor/mapper/OrderMapper.java
  src/main/java/com/smart/tailor/service/impl/OrderServiceImpl.java
  src/main/java/com/smart/tailor/service/impl/ScheduleTaskServiceImpl.java
Labels: bug, function, update, Fix Code

#199 [BE0073] update notification status and mark all read
  src/main/java/com/smart/tailor/constant/APIConstant.java
  src/main/java/com/smart/tailor/constant/MessageConstant.java
  src/main/java/com/smart/tailor/controller/NotificationController.java
  src/main/java/com/smart/tailor/service/NotificationService.java
  src/main/java/com/smart/tailor/service/impl/NotificationServiceImpl.java
  src/main/java/com/smart/tailor/utils/response/NotificationResponse.java
Labels: function, update

#201 Feature be0061 rating order
  src/main/java/com/smart/tailor/service/BrandService.java
  src/main/java/com/smart/tailor/service/impl/BrandServiceImpl.java
  src/main/java/com/smart/tailor/service/impl/OrderServiceImpl.java
  src/main/java/com/smart/tailor/utils/request/RatingOrderRequest.java
Labels: function, update, Fix Code

#202 Feature be0072 flow cancel order
  src/main/java/com/smart/tailor/constant/APIConstant.java
  src/main/java/com/smart/tailor/controller/PaymentController.java
  src/main/java/com/smart/tailor/entities/Order.java
  src/main/java/com/smart/tailor/enums/PaymentType.java
  src/main/java/com/smart/tailor/mapper/OrderMapper.java
  src/main/java/com/smart/tailor/service/PaymentService.java
  src/main/java/com/smart/tailor/service/impl/DesignDetailServiceImpl.java
  src/main/java/com/smart/tailor/service/impl/DesignServiceImpl.java
  src/main/java/com/smart/tailor/service/impl/OrderServiceImpl.java
  src/main/java/com/smart/tailor/service/impl/PartOfDesignServiceImpl.java
  src/main/java/com/smart/tailor/service/impl/PayOSServiceImpl.java
  src/main/java/com/smart/tailor/service/impl/PaymentServiceImpl.java
  src/main/java/com/smart/tailor/service/impl/ScheduleTaskServiceImpl.java
  src/main/java/com/smart/tailor/utils/Utilities.java
  src/main/java/com/smart/tailor/utils/response/OrderDetailResponse.java
  src/main/resources/application.properties
  src/main/resources/smartTailorScript.sql
Labels: function, update, Fix Code

#203 [BE0038] add get all payment
  src/main/java/com/smart/tailor/constant/APIConstant.java
  src/main/java/com/smart/tailor/controller/PaymentController.java
  src/main/java/com/smart/tailor/service/PaymentService.java
  src/main/java/com/smart/tailor/service/impl/PaymentServiceImpl.java
Labels: function, update

#200 Feature be0076 create resource based access control
  src/main/java/com/smart/tailor/config/SecurityConfig.java
  src/main/java/com/smart/tailor/controller/BrandLaborQuantityController.java
  src/main/java/com/smart/tailor/controller/BrandMaterialController.java
  src/main/java/com/smart/tailor/controller/CustomerController.java
  src/main/java/com/smart/tailor/controller/DesignController.java
  src/main/java/com/smart/tailor/controller/DesignDetailController.java
  src/main/java/com/smart/tailor/controller/NotificationController.java
  src/main/java/com/smart/tailor/controller/OrderController.java
  src/main/java/com/smart/tailor/controller/ReportController.java
  src/main/java/com/smart/tailor/exception/UnauthorizedAccessException.java
  src/main/java/com/smart/tailor/exception/handler/GlobalExceptionHandler.java
  src/main/java/com/smart/tailor/service/BrandLaborQuantityService.java
  src/main/java/com/smart/tailor/service/BrandMaterialService.java
  src/main/java/com/smart/tailor/service/CustomerService.java
  src/main/java/com/smart/tailor/service/DesignDetailService.java
  src/main/java/com/smart/tailor/service/DesignService.java
  src/main/java/com/smart/tailor/service/JwtService.java
  src/main/java/com/smart/tailor/service/NotificationService.java
  src/main/java/com/smart/tailor/service/OrderService.java
  src/main/java/com/smart/tailor/service/ReportService.java
  src/main/java/com/smart/tailor/service/impl/BrandLaborQuantityServiceImpl.java
  src/main/java/com/smart/tailor/service/impl/BrandMaterialServiceImpl.java
  src/main/java/com/smart/tailor/service/impl/CustomerServiceImpl.java
  src/main/java/com/smart/tailor/service/impl/DesignDetailServiceImpl.java
  src/main/java/com/smart/tailor/service/impl/DesignServiceImpl.java
  src/main/java/com/smart/tailor/service/impl/JwtServiceImpl.java
  src/main/java/com/smart/tailor/service/impl/NotificationServiceImpl.java
  src/main/java/com/smart/tailor/service/impl/OrderServiceImpl.java
  src/main/java/com/smart/tailor/service/impl/ReportServiceImpl.java
  src/main/resources/application.properties
Labels: function, update, Fix Code

#205 Update Brand Rating When Cancel Before or After Starting Order
  src/main/java/com/smart/tailor/service/BrandService.java
  src/main/java/com/smart/tailor/service/impl/BrandServiceImpl.java
  src/main/java/com/smart/tailor/service/impl/OrderServiceImpl.java
  src/main/resources/smartTailorScript.sql
Labels: function, update, Fix Code

#208 Feature be0073 notification feature
  src/main/java/com/smart/tailor/service/impl/OrderServiceImpl.java
  src/main/java/com/smart/tailor/service/impl/ScheduleTaskServiceImpl.java
Labels: bug, update, Fix Code

#207 [BE0074] Create OrderTimeLine for SubOrder along with Customer Payment
  src/main/java/com/smart/tailor/SmartTailorBeApplication.java
  src/main/java/com/smart/tailor/constant/APIConstant.java
  src/main/java/com/smart/tailor/controller/OrderController.java
  src/main/java/com/smart/tailor/repository/OrderRepository.java
  src/main/java/com/smart/tailor/service/OrderService.java
  src/main/java/com/smart/tailor/service/impl/OrderServiceImpl.java
  src/main/java/com/smart/tailor/utils/response/OrderTimeLineResponse.java
Labels: function, update

#209 Feature be0077 update design partofdesign itemmask
  src/main/java/com/smart/tailor/entities/ItemMask.java
  src/main/java/com/smart/tailor/entities/PartOfDesign.java
  src/main/java/com/smart/tailor/mapper/ItemMaskMapper.java
  src/main/java/com/smart/tailor/repository/ItemMaskRepository.java
  src/main/java/com/smart/tailor/repository/PartOfDesignRepository.java
  src/main/java/com/smart/tailor/service/ItemMaskService.java
  src/main/java/com/smart/tailor/service/PartOfDesignService.java
  src/main/java/com/smart/tailor/service/impl/DesignDetailServiceImpl.java
  src/main/java/com/smart/tailor/service/impl/DesignServiceImpl.java
  src/main/java/com/smart/tailor/service/impl/ItemMaskServiceImpl.java
  src/main/java/com/smart/tailor/service/impl/PartOfDesignServiceImpl.java
  src/main/java/com/smart/tailor/utils/response/ItemMaskResponse.java
Labels: function, update, Fix Code

#210 [BE0078] update order price
  src/main/java/com/smart/tailor/service/impl/OrderServiceImpl.java
  src/main/java/com/smart/tailor/service/impl/ScheduleTaskServiceImpl.java
Labels: bug, function, update, Fix Code

#211 Feature be0079 create api to draw chart
  src/main/java/com/smart/tailor/SmartTailorBeApplication.java
  src/main/java/com/smart/tailor/config/SecurityConfig.java
  src/main/java/com/smart/tailor/constant/APIConstant.java
  src/main/java/com/smart/tailor/controller/OrderController.java
  src/main/java/com/smart/tailor/controller/PaymentController.java
  src/main/java/com/smart/tailor/controller/UserController.java
  src/main/java/com/smart/tailor/repository/OrderRepository.java
  src/main/java/com/smart/tailor/service/OrderService.java
  src/main/java/com/smart/tailor/service/PaymentService.java
  src/main/java/com/smart/tailor/service/UserService.java
  src/main/java/com/smart/tailor/service/impl/OrderServiceImpl.java
  src/main/java/com/smart/tailor/service/impl/PaymentServiceImpl.java
  src/main/java/com/smart/tailor/service/impl/UserServiceImpl.java
  src/main/java/com/smart/tailor/utils/response/OrderStatusDetailResponse.java
Labels: function

#212 Update Auditing in Entity
  .run/SmartTailorBeApplication.run.xml
  src/main/java/com/smart/tailor/SmartTailorBeApplication.java
  src/main/java/com/smart/tailor/config/SecurityConfig.java
  src/main/java/com/smart/tailor/entities/AuditEntity.java
  src/main/java/com/smart/tailor/entities/Brand.java
  src/main/java/com/smart/tailor/entities/BrandExpertTailoring.java
  src/main/java/com/smart/tailor/entities/BrandImage.java
  src/main/java/com/smart/tailor/entities/BrandLaborQuantity.java
  src/main/java/com/smart/tailor/entities/BrandMaterial.java
  src/main/java/com/smart/tailor/entities/BrandProperties.java
  src/main/java/com/smart/tailor/entities/Category.java
  src/main/java/com/smart/tailor/entities/Customer.java
  src/main/java/com/smart/tailor/entities/Design.java
  src/main/java/com/smart/tailor/entities/DesignDetail.java
  src/main/java/com/smart/tailor/entities/Employee.java
  src/main/java/com/smart/tailor/entities/ExpertTailoring.java
  src/main/java/com/smart/tailor/entities/ExpertTailoringMaterial.java
  src/main/java/com/smart/tailor/entities/ItemMask.java
  src/main/java/com/smart/tailor/entities/LaborQuantity.java
  src/main/java/com/smart/tailor/entities/Material.java
  src/main/java/com/smart/tailor/entities/Notification.java
  src/main/java/com/smart/tailor/entities/Order.java
  src/main/java/com/smart/tailor/entities/OrderStage.java
  src/main/java/com/smart/tailor/entities/PartOfDesign.java
  src/main/java/com/smart/tailor/entities/PayOSData.java
  src/main/java/com/smart/tailor/entities/Payment.java
  src/main/java/com/smart/tailor/entities/Report.java
  src/main/java/com/smart/tailor/entities/ReportImage.java
  src/main/java/com/smart/tailor/entities/Roles.java
  src/main/java/com/smart/tailor/entities/SampleProductData.java
  src/main/java/com/smart/tailor/entities/Size.java
  src/main/java/com/smart/tailor/entities/SizeExpertTailoring.java
  src/main/java/com/smart/tailor/entities/SystemImage.java
  src/main/java/com/smart/tailor/entities/SystemProperties.java
  src/main/java/com/smart/tailor/entities/Task.java
  src/main/java/com/smart/tailor/entities/Token.java
  src/main/java/com/smart/tailor/entities/User.java
  src/main/java/com/smart/tailor/entities/UsingNotification.java
  src/main/java/com/smart/tailor/entities/VerificationToken.java
Labels: function, update, Fix Code

#213 Feature be0079 create api to draw chart
  .run/SmartTailorBeApplication.run.xml
  pom.xml
  src/main/java/com/smart/tailor/config/SecurityConfig.java
  src/main/java/com/smart/tailor/constant/APIConstant.java
  src/main/java/com/smart/tailor/controller/OrderController.java
  src/main/java/com/smart/tailor/controller/PaymentController.java
  src/main/java/com/smart/tailor/controller/UserController.java
  src/main/java/com/smart/tailor/entities/Brand.java
  src/main/java/com/smart/tailor/entities/BrandImage.java
  src/main/java/com/smart/tailor/exception/handler/GlobalExceptionHandler.java
  src/main/java/com/smart/tailor/mapper/BrandImageMapper.java
  src/main/java/com/smart/tailor/mapper/BrandMapper.java
  src/main/java/com/smart/tailor/service/OrderService.java
  src/main/java/com/smart/tailor/service/PaymentService.java
  src/main/java/com/smart/tailor/service/UserService.java
  src/main/java/com/smart/tailor/service/impl/OrderServiceImpl.java
  src/main/java/com/smart/tailor/service/impl/PaymentServiceImpl.java
  src/main/java/com/smart/tailor/service/impl/UserServiceImpl.java
  src/main/java/com/smart/tailor/utils/response/BrandImageResponse.java
  src/main/java/com/smart/tailor/utils/response/GrowthPercentageResponse.java
  src/main/java/com/smart/tailor/validate/ValidEnumValueConstraint.java
Labels: function, update

#214 Feature be0079 create api to draw chart
  .run/SmartTailorBeApplication.run.xml
  src/main/java/com/smart/tailor/config/SecurityConfig.java
  src/main/java/com/smart/tailor/constant/APIConstant.java
  src/main/java/com/smart/tailor/controller/PaymentController.java
  src/main/java/com/smart/tailor/service/PaymentService.java
  src/main/java/com/smart/tailor/service/impl/PaymentServiceImpl.java
  src/main/java/com/smart/tailor/utils/response/GrowthPercentageResponse.java
Labels: function, update

#216 [BE0032] update order status
  src/main/java/com/smart/tailor/controller/PaymentController.java
  src/main/java/com/smart/tailor/enums/OrderStatus.java
Labels: update

#218 Create Clone Design From BaseDesign and add to DesignDetail
  src/main/java/com/smart/tailor/constant/APIConstant.java
  src/main/java/com/smart/tailor/controller/DesignController.java
  src/main/java/com/smart/tailor/repository/DesignRepository.java
  src/main/java/com/smart/tailor/service/DesignService.java
  src/main/java/com/smart/tailor/service/ItemMaskService.java
  src/main/java/com/smart/tailor/service/PartOfDesignService.java
  src/main/java/com/smart/tailor/service/impl/DesignDetailServiceImpl.java
  src/main/java/com/smart/tailor/service/impl/DesignServiceImpl.java
  src/main/java/com/smart/tailor/service/impl/ItemMaskServiceImpl.java
  src/main/java/com/smart/tailor/service/impl/PartOfDesignServiceImpl.java
Labels: function, update

#220 Feature be0067 update and fix code
  src/main/java/com/smart/tailor/controller/OrderController.java
  src/main/java/com/smart/tailor/service/OrderService.java
  src/main/java/com/smart/tailor/service/impl/DesignDetailServiceImpl.java
  src/main/java/com/smart/tailor/service/impl/OrderServiceImpl.java
Labels: function, update, Fix Code

#221 Fix Code and Get Invoice by SubOrderID
  src/main/java/com/smart/tailor/config/SecurityConfig.java
  src/main/java/com/smart/tailor/constant/APIConstant.java
  src/main/java/com/smart/tailor/controller/OrderController.java
  src/main/java/com/smart/tailor/repository/BrandMaterialRepository.java
  src/main/java/com/smart/tailor/service/BrandMaterialService.java
  src/main/java/com/smart/tailor/service/OrderService.java
  src/main/java/com/smart/tailor/service/impl/BrandMaterialServiceImpl.java
  src/main/java/com/smart/tailor/service/impl/OrderServiceImpl.java
  src/main/java/com/smart/tailor/utils/response/BrandLaborQuantityResponse.java
  src/main/java/com/smart/tailor/utils/response/LaborQuantityResponse.java
  src/main/java/com/smart/tailor/utils/response/SubOrderInvoice.java
Labels: function, update

#222 [BE0078] update price error
  src/main/java/com/smart/tailor/service/impl/OrderServiceImpl.java
  src/main/java/com/smart/tailor/service/impl/PaymentServiceImpl.java
Labels: bug, update, Fix Code

#223 [BE0078] update sub order price
  src/main/java/com/smart/tailor/service/impl/OrderServiceImpl.java
Labels: update, Fix Code

#225 Feature be0082 create design detail material by parent order
  src/main/java/com/smart/tailor/config/SecurityConfig.java
  src/main/java/com/smart/tailor/controller/DesignController.java
  src/main/java/com/smart/tailor/entities/Order.java
  src/main/java/com/smart/tailor/service/DesignService.java
  src/main/java/com/smart/tailor/service/ScheduleTaskService.java
  src/main/java/com/smart/tailor/service/impl/DesignDetailServiceImpl.java
  src/main/java/com/smart/tailor/service/impl/DesignServiceImpl.java
  src/main/java/com/smart/tailor/service/impl/OrderServiceImpl.java
  src/main/java/com/smart/tailor/service/impl/ScheduleTaskServiceImpl.java
  src/main/java/com/smart/tailor/utils/request/ItemMaskInformation.java
  src/main/java/com/smart/tailor/utils/request/PartOfDesignInformation.java
  src/main/java/com/smart/tailor/utils/response/DesignMaterialDetailResponse.java
  src/main/java/com/smart/tailor/utils/response/DesignMaterialResponse.java
  src/main/java/com/smart/tailor/utils/response/OrderCustomResponse.java
  src/main/java/com/smart/tailor/utils/response/OrderDetailPriceResponse.java
  src/main/resources/smartTailorScript.sql
Labels: function, update, Fix Code

#226 [BE0032] update get fullorder
  src/main/java/com/smart/tailor/service/impl/DesignServiceImpl.java
  src/main/java/com/smart/tailor/service/impl/OrderServiceImpl.java
  src/main/java/com/smart/tailor/service/impl/PayOSDataServiceImpl.java
  src/main/java/com/smart/tailor/service/impl/PaymentServiceImpl.java
  src/main/java/com/smart/tailor/service/impl/ScheduleTaskServiceImpl.java
  src/main/java/com/smart/tailor/utils/response/PayOSDataResponse.java
Labels: update, Fix Code

#227 Feature be0082 create design detail material by parent order
  src/main/java/com/smart/tailor/service/impl/OrderServiceImpl.java
  src/main/resources/smartTailorScript.sql
Labels: function, update

#229 Add Security to Manager to manage Brand
  src/main/java/com/smart/tailor/config/SecurityConfig.java
Labels: function, update, Fix Code

#230 Add Security to UpdateUser
  src/main/java/com/smart/tailor/config/SecurityConfig.java
Labels: function, update, Fix Code

#231 Update Data for Fabric and Thread
  src/main/java/com/smart/tailor/config/SecurityConfig.java
  src/main/resources/smartTailorScript.sql
Labels: function, update, Fix Code

#232 Update Script for Manual Printing and Heat Printing
  src/main/java/com/smart/tailor/config/SecurityConfig.java
  src/main/resources/application.properties
  src/main/resources/smartTailorScript.sql
Labels: function, update, Fix Code

#233 Update PrintType
  src/main/java/com/smart/tailor/enums/PrintType.java
Labels: function, update, Fix Code

#234 [BE0067] sort order, payment, report by created_date
  src/main/java/com/smart/tailor/mapper/OrderMapper.java
  src/main/java/com/smart/tailor/service/impl/OrderServiceImpl.java
  src/main/java/com/smart/tailor/service/impl/PaymentServiceImpl.java
  src/main/java/com/smart/tailor/service/impl/ReportServiceImpl.java
  src/main/resources/application.properties
Labels: function, update, Fix Code

#235 [BE0067] fix missing order refund transaction
  src/main/java/com/smart/tailor/service/impl/OrderServiceImpl.java
Labels: update, Fix Code

#238 Update Code BrandExpertTailoring
  src/main/java/com/smart/tailor/config/SecurityConfig.java
  src/main/java/com/smart/tailor/constant/APIConstant.java
  src/main/java/com/smart/tailor/controller/BrandController.java
  src/main/java/com/smart/tailor/entities/BrandExpertTailoring.java
  src/main/java/com/smart/tailor/entities/BrandExpertTailoringKey.java
  src/main/java/com/smart/tailor/service/BrandExpertTailoringService.java
  src/main/java/com/smart/tailor/service/impl/BrandExpertTailoringServiceImpl.java
  src/main/java/com/smart/tailor/utils/request/BrandExpertTailoringRequest.java
  src/main/java/com/smart/tailor/utils/response/BrandExpertTailoringResponse.java
Labels: function, update, Fix Code

#239 Update Error Response
  src/main/java/com/smart/tailor/service/impl/BrandExpertTailoringServiceImpl.java
Labels: function, update, Fix Code
