Repository TTTM-Mavericks/smart-tailor-BE, pull requests merged in 2024-07, with the labels that each got.

#51 [BE0031] Create Design Detail
  src/main/java/com/smart/tailor/constant/APIConstant.java
  src/main/java/com/smart/tailor/constant/MessageConstant.java
  src/main/java/com/smart/tailor/controller/DesignDetailController.java
  src/main/java/com/smart/tailor/entities/DesignDetail.java
  src/main/java/com/smart/tailor/mapper/DesignDetailMapper.java
  src/main/java/com/smart/tailor/repository/DesignDetailRepository.java
  src/main/java/com/smart/tailor/service/DesignDetailService.java
  src/main/java/com/smart/tailor/service/OrderService.java
  src/main/java/com/smart/tailor/service/impl/DesignDetailServiceImpl.java
  src/main/java/com/smart/tailor/service/impl/OrderServiceImpl.java
  src/main/java/com/smart/tailor/utils/request/DesignDetailRequest.java
  src/main/java/com/smart/tailor/utils/response/DesignDetailResponse.java
Labels: function

#52 [BE0032] Create Order
  src/main/java/com/smart/tailor/constant/APIConstant.java
  src/main/java/com/smart/tailor/constant/MessageConstant.java
  src/main/java/com/smart/tailor/controller/OrderController.java
  src/main/java/com/smart/tailor/service/OrderService.java
  src/main/java/com/smart/tailor/service/impl/OrderServiceImpl.java
  src/main/java/com/smart/tailor/utils/request/OrderRequest.java
Labels: function

#53 [BE0032] update create order
  src/main/java/com/smart/tailor/service/impl/OrderServiceImpl.java
  src/main/java/com/smart/tailor/utils/request/OrderRequest.java
Labels: update

#56 [BE0027] Update Design Detail Table
  src/main/java/com/smart/tailor/entities/DesignDetail.java
  src/main/java/com/smart/tailor/repository/DesignDetailRepository.java
  src/main/java/com/smart/tailor/service/DesignDetailService.java
  src/main/java/com/smart/tailor/service/SizeService.java
  src/main/java/com/smart/tailor/service/SizeServiceImpl.java
  src/main/java/com/smart/tailor/service/impl/DesignDetailServiceImpl.java
  src/main/java/com/smart/tailor/utils/request/DesignDetailRequest.java
  src/main/java/com/smart/tailor/utils/response/DesignDetailResponse.java
  src/main/resources/application.properties
Labels: update

#57 [BE0042] Update Design, PartOfDesign, ItemMask along with Material
  src/main/java/com/smart/tailor/constant/APIConstant.java
  src/main/java/com/smart/tailor/constant/MessageConstant.java
  src/main/java/com/smart/tailor/controller/DesignController.java
  src/main/java/com/smart/tailor/entities/Design.java
  src/main/java/com/smart/tailor/entities/PartOfDesign.java
  src/main/java/com/smart/tailor/repository/ItemMaskRepository.java
  src/main/java/com/smart/tailor/repository/PartOfDesignRepository.java
  src/main/java/com/smart/tailor/service/DesignService.java
  src/main/java/com/smart/tailor/service/ItemMaskService.java
  src/main/java/com/smart/tailor/service/PartOfDesignService.java
  src/main/java/com/smart/tailor/service/impl/DesignServiceImpl.java
  src/main/java/com/smart/tailor/service/impl/ItemMaskServiceImpl.java
  src/main/java/com/smart/tailor/service/impl/PartOfDesignServiceImpl.java
  src/main/java/com/smart/tailor/utils/request/DesignRequest.java
  src/main/java/com/smart/tailor/utils/request/UpdateDesignRequest.java
  src/main/resources/application.properties
Labels: update

#59 [[BE0045] Update Choosing Materials
  src/main/java/com/smart/tailor/constant/APIConstant.java
  src/main/java/com/smart/tailor/constant/MessageConstant.java
  src/main/java/com/smart/tailor/controller/MaterialController.java
Labels: function, update

#60 [BE0045] update choosing materials - get list material by categiry name
  src/main/java/com/smart/tailor/constant/APIConstant.java
  src/main/java/com/smart/tailor/constant/MessageConstant.java
  src/main/java/com/smart/tailor/controller/MaterialController.java
  src/main/java/com/smart/tailor/repository/MaterialRepository.java
  src/main/java/com/smart/tailor/service/MaterialService.java
  src/main/java/com/smart/tailor/service/impl/MaterialServiceImpl.java
Labels: function, update

#61 [BE0012] Update Database Entity Expert_Tailoring
  src/main/java/com/smart/tailor/SmartTailorBeApplication.java
  src/main/java/com/smart/tailor/entities/ExpertTailoring.java
  src/main/java/com/smart/tailor/service/impl/ExpertTailoringServiceImpl.java
  src/main/java/com/smart/tailor/utils/request/ExpertTailoringRequest.java
  src/main/java/com/smart/tailor/utils/response/ExpertTailoringResponse.java
Labels: update

#63 [BE0046] Create System Image
  src/main/java/com/smart/tailor/constant/APIConstant.java
  src/main/java/com/smart/tailor/constant/MessageConstant.java
  src/main/java/com/smart/tailor/controller/SystemImageController.java
  src/main/java/com/smart/tailor/mapper/SystemImageMapper.java
  src/main/java/com/smart/tailor/repository/SystemImageRepository.java
  src/main/java/com/smart/tailor/service/SystemImageService.java
  src/main/java/com/smart/tailor/service/impl/SystemImageServiceImpl.java
  src/main/java/com/smart/tailor/utils/request/SystemImageRequest.java
  src/main/java/com/smart/tailor/utils/response/SystemImageResponse.java
Labels: function

#66 [BE0042] Update Design by Keeping Old DesignID and Removing PartOfDesign and ItemMask
  src/main/java/com/smart/tailor/repository/ItemMaskRepository.java
  src/main/java/com/smart/tailor/repository/PartOfDesignRepository.java
  src/main/java/com/smart/tailor/service/ItemMaskService.java
  src/main/java/com/smart/tailor/service/PartOfDesignService.java
  src/main/java/com/smart/tailor/service/impl/DesignServiceImpl.java
  src/main/java/com/smart/tailor/service/impl/ItemMaskServiceImpl.java
  src/main/java/com/smart/tailor/service/impl/PartOfDesignServiceImpl.java
Labels: function, update

#68 [BE0042] Update Material Price When Create Design, Part Of Design, ItemMask
  src/main/java/com/smart/tailor/mapper/DesignMapper.java
  src/main/java/com/smart/tailor/repository/BrandMaterialRepository.java
  src/main/java/com/smart/tailor/service/BrandMaterialService.java
  src/main/java/com/smart/tailor/service/impl/BrandMaterialServiceImpl.java
  src/main/java/com/smart/tailor/service/impl/DesignServiceImpl.java
  src/main/java/com/smart/tailor/utils/response/DesignMaterialDetail.java
  src/main/java/com/smart/tailor/utils/response/DesignResponse.java
Labels: function, update

#69 [BE0042] Update Material Detail in Design
  src/main/java/com/smart/tailor/repository/BrandMaterialRepository.java
  src/main/java/com/smart/tailor/service/impl/BrandMaterialServiceImpl.java
Labels: update

#70 [BE0042] Rename ItemMask To ItemMasks
  src/main/java/com/smart/tailor/mapper/PartOfDesignMapper.java
  src/main/java/com/smart/tailor/service/impl/DesignServiceImpl.java
  src/main/java/com/smart/tailor/utils/response/PartOfDesignResponse.java
Labels: update

#71 [BE0032] Update CRUD Order
  src/main/java/com/smart/tailor/SmartTailorBeApplication.java
  src/main/java/com/smart/tailor/constant/APIConstant.java
  src/main/java/com/smart/tailor/constant/MessageConstant.java
  src/main/java/com/smart/tailor/controller/OrderController.java
  src/main/java/com/smart/tailor/repository/CustomerRepository.java
  src/main/java/com/smart/tailor/service/OrderService.java
  src/main/java/com/smart/tailor/service/impl/CustomerServiceImpl.java
  src/main/java/com/smart/tailor/service/impl/OrderServiceImpl.java
Labels: function, update

#72 [BE0032] Update find customer in create Order
  src/main/java/com/smart/tailor/controller/OrderController.java
  src/main/java/com/smart/tailor/repository/CustomerRepository.java
Labels: update

#73 [BE0006] Update Auth Register User - Create Customer when register Us…
  src/main/java/com/smart/tailor/service/CustomerService.java
  src/main/java/com/smart/tailor/service/impl/AuthenticationServiceImpl.java
  src/main/java/com/smart/tailor/service/impl/CustomerServiceImpl.java
Labels: function, update

#74 [BE0032] Update get Order By ID
  src/main/java/com/smart/tailor/controller/OrderController.java
Labels: function, update

#76 [BE0032] Update order created
  src/main/java/com/smart/tailor/mapper/ExpertTailoringMapper.java
  src/main/java/com/smart/tailor/service/impl/OrderServiceImpl.java
  src/main/java/com/smart/tailor/utils/response/ExpertTailoringResponse.java
Labels: function, update

#77 [BE0032] Update DesignResponse into OrderResponse
  src/main/java/com/smart/tailor/mapper/OrderMapper.java
  src/main/java/com/smart/tailor/repository/DesignRepository.java
  src/main/java/com/smart/tailor/service/DesignService.java
  src/main/java/com/smart/tailor/service/impl/DesignServiceImpl.java
  src/main/java/com/smart/tailor/service/impl/OrderServiceImpl.java
Labels: function, update

#79 [BE0032] update create order
  src/main/java/com/smart/tailor/service/impl/DesignDetailServiceImpl.java
  src/main/java/com/smart/tailor/service/impl/OrderServiceImpl.java
  src/main/java/com/smart/tailor/utils/request/DesignDetailRequest.java
Labels: function, update

#82 [BE0031] Update Get Design Detail By Order ID
  src/main/java/com/smart/tailor/constant/APIConstant.java
  src/main/java/com/smart/tailor/controller/DesignDetailController.java
  src/main/java/com/smart/tailor/repository/DesignDetailRepository.java
  src/main/java/com/smart/tailor/service/DesignDetailService.java
  src/main/java/com/smart/tailor/service/impl/DesignDetailServiceImpl.java
  src/main/java/com/smart/tailor/service/impl/OrderServiceImpl.java
Labels: function, update

#86 [BE0031] update order response
  src/main/java/com/smart/tailor/mapper/OrderMapper.java
  src/main/java/com/smart/tailor/service/OrderService.java
  src/main/java/com/smart/tailor/service/impl/DesignDetailServiceImpl.java
  src/main/java/com/smart/tailor/service/impl/OrderServiceImpl.java
  src/main/java/com/smart/tailor/utils/response/DesignDetailCustomResponse.java
  src/main/java/com/smart/tailor/utils/response/OrderCustomResponse.java
Labels: update

#89 [BE0052] Update Orderstatus (for function employee verify before order)
  src/main/java/com/smart/tailor/constant/APIConstant.java
  src/main/java/com/smart/tailor/constant/MessageConstant.java
  src/main/java/com/smart/tailor/controller/OrderController.java
  src/main/java/com/smart/tailor/enums/OrderStatus.java
  src/main/java/com/smart/tailor/service/OrderService.java
  src/main/java/com/smart/tailor/service/impl/OrderServiceImpl.java
  src/main/java/com/smart/tailor/utils/request/OrderStatusUpdateRequest.java
Labels: function, update

#90 [BE0032] Update Design Response when Create Order
  src/main/java/com/smart/tailor/service/impl/DesignServiceImpl.java
  src/main/java/com/smart/tailor/utils/response/DesignMaterialDetail.java
Labels: function, update

#91 [BE0032] Update Create Design
  src/main/java/com/smart/tailor/service/impl/DesignServiceImpl.java
Labels: update

#92 [BE0032] update create design
  src/main/java/com/smart/tailor/service/impl/DesignServiceImpl.java
Labels: update

#93 [BE0053] Brand Pick An Order
  src/main/java/com/smart/tailor/constant/APIConstant.java
  src/main/java/com/smart/tailor/constant/MessageConstant.java
  src/main/java/com/smart/tailor/controller/OrderController.java
  src/main/java/com/smart/tailor/repository/DesignDetailRepository.java
  src/main/java/com/smart/tailor/repository/OrderRepository.java
  src/main/java/com/smart/tailor/service/DesignDetailService.java
  src/main/java/com/smart/tailor/service/OrderService.java
  src/main/java/com/smart/tailor/service/impl/DesignDetailServiceImpl.java
  src/main/java/com/smart/tailor/service/impl/OrderServiceImpl.java
  src/main/java/com/smart/tailor/utils/request/OrderPickingRequest.java
  src/main/java/com/smart/tailor/utils/request/OrderRequest.java
Labels: function, update

#94 [BE0016] crud brand
  src/main/java/com/smart/tailor/controller/BrandController.java
  src/main/java/com/smart/tailor/service/impl/BrandServiceImpl.java
Labels: update

#95 [BE0032] update crud order
  src/main/java/com/smart/tailor/service/impl/OrderServiceImpl.java
  src/main/java/com/smart/tailor/utils/request/OrderPickingRequest.java
  src/main/java/com/smart/tailor/utils/response/OrderDetailResponse.java
  src/main/java/com/smart/tailor/utils/response/SubOrderResponse.java
Labels: update

#96 [BE0016] crud brand update
  src/main/java/com/smart/tailor/controller/BrandController.java
  src/main/java/com/smart/tailor/service/BrandService.java
  src/main/java/com/smart/tailor/service/impl/BrandServiceImpl.java
  src/main/java/com/smart/tailor/utils/request/BrandRequest.java
Labels: update

#97 [BE0016] update brand
  src/main/java/com/smart/tailor/constant/ErrorConstant.java
  src/main/java/com/smart/tailor/controller/BrandController.java
Labels: update

#98 [BE0032] update orderResponse, designResponse, DetailResponse when ceate order
  src/main/java/com/smart/tailor/constant/APIConstant.java
  src/main/java/com/smart/tailor/controller/DesignDetailController.java
  src/main/java/com/smart/tailor/controller/OrderController.java
  src/main/java/com/smart/tailor/entities/Order.java
  src/main/java/com/smart/tailor/mapper/OrderMapper.java
  src/main/java/com/smart/tailor/repository/DesignDetailRepository.java
  src/main/java/com/smart/tailor/repository/DesignRepository.java
  src/main/java/com/smart/tailor/service/DesignDetailService.java
  src/main/java/com/smart/tailor/service/impl/DesignDetailServiceImpl.java
  src/main/java/com/smart/tailor/service/impl/OrderServiceImpl.java
  src/main/java/com/smart/tailor/utils/request/OrderRequest.java
  src/main/java/com/smart/tailor/utils/response/OrderCustomResponse.java
  src/main/java/com/smart/tailor/utils/response/OrderResponse.java
Labels: function, update

#99 [BE0032] update order status
  src/main/java/com/smart/tailor/enums/OrderStatus.java
Labels: update

#100 [BE0032] update order response based on order_type
  src/main/java/com/smart/tailor/repository/DesignDetailRepository.java
  src/main/java/com/smart/tailor/service/impl/OrderServiceImpl.java
Labels: update

#101 [BE0054] Update And Fix Code Category Material
  src/main/java/com/smart/tailor/constant/APIConstant.java
  src/main/java/com/smart/tailor/controller/CategoryController.java
  src/main/java/com/smart/tailor/entities/Category.java
  src/main/java/com/smart/tailor/exception/ExcelFileInvalidDataTypeException.java
  src/main/java/com/smart/tailor/exception/InvalidInputException.java
  src/main/java/com/smart/tailor/exception/MultipleErrorException.java
  src/main/java/com/smart/tailor/exception/handler/ExcelExceptionHandler.java
  src/main/java/com/smart/tailor/exception/handler/GlobalExceptionHandler.java
  src/main/java/com/smart/tailor/mapper/CategoryMapper.java
  src/main/java/com/smart/tailor/repository/CategoryRepository.java
  src/main/java/com/smart/tailor/repository/MaterialRepository.java
  src/main/java/com/smart/tailor/service/CategoryService.java
  src/main/java/com/smart/tailor/service/impl/BrandMaterialServiceImpl.java
  src/main/java/com/smart/tailor/service/impl/CategoryServiceImpl.java
  src/main/java/com/smart/tailor/service/impl/ExpertTailoringMaterialServiceImpl.java
  src/main/java/com/smart/tailor/service/impl/ExpertTailoringServiceImpl.java
  src/main/java/com/smart/tailor/service/impl/MaterialServiceImpl.java
  src/main/java/com/smart/tailor/service/impl/SizeExpertTailoringServiceImpl.java
  src/main/java/com/smart/tailor/utils/request/CategoryListRequest.java
  src/main/java/com/smart/tailor/utils/request/CategoryRequest.java
  src/main/java/com/smart/tailor/utils/response/CategoryResponse.java
  src/main/java/com/smart/tailor/utils/response/ErrorDetail.java
Labels: function, update, Fix Code

#103 [BE0055] Update Code BrandMaterial, PartOfDesign and ItemMask
  src/main/java/com/smart/tailor/entities/BrandMaterial.java
  src/main/java/com/smart/tailor/entities/BrandMaterialKey.java
  src/main/java/com/smart/tailor/mapper/BrandMaterialMapper.java
  src/main/java/com/smart/tailor/service/impl/BrandMaterialServiceImpl.java
  src/main/java/com/smart/tailor/service/impl/ItemMaskServiceImpl.java
  src/main/java/com/smart/tailor/service/impl/MaterialServiceImpl.java
  src/main/java/com/smart/tailor/service/impl/PartOfDesignServiceImpl.java
  src/main/java/com/smart/tailor/utils/Utilities.java
  src/main/java/com/smart/tailor/utils/request/ItemMaskRequest.java
  src/main/java/com/smart/tailor/utils/request/PartOfDesignRequest.java
Labels: function, update, Fix Code

#105 Update And Fix Code PartOfDesign ItemMask Material and Size
  src/main/java/com/smart/tailor/repository/MaterialRepository.java
  src/main/java/com/smart/tailor/service/ExcelImportService.java
  src/main/java/com/smart/tailor/service/MaterialService.java
  src/main/java/com/smart/tailor/service/SizeServiceImpl.java
  src/main/java/com/smart/tailor/service/impl/ExcelImportServiceImpl.java
  src/main/java/com/smart/tailor/service/impl/LaborQuantityServiceImpl.java
  src/main/java/com/smart/tailor/service/impl/MaterialServiceImpl.java
  src/main/java/com/smart/tailor/service/impl/PartOfDesignServiceImpl.java
Labels: function, update, Fix Code

#106 [BE0016] update brand creation
  src/main/java/com/smart/tailor/service/impl/BrandServiceImpl.java
  src/main/java/com/smart/tailor/utils/request/BrandRequest.java
  src/main/java/com/smart/tailor/utils/response/BrandResponse.java
Labels: update, Fix Code

#107 Fix Code Design, PartOfDesign with ImageUrl
  src/main/java/com/smart/tailor/service/impl/DesignServiceImpl.java
Labels: Fix Code

#108 [BE0016] update brand infor request
  src/main/java/com/smart/tailor/service/impl/BrandServiceImpl.java
  src/main/java/com/smart/tailor/utils/request/BrandRequest.java
Labels: bug, update, Fix Code

#109 [BE0026] updae design response
  src/main/java/com/smart/tailor/service/impl/DesignServiceImpl.java
Labels: bug, update, Fix Code

#110 Feature be0016 crud brand
  src/main/java/com/smart/tailor/controller/BrandController.java
  src/main/java/com/smart/tailor/service/impl/BrandServiceImpl.java
Labels: update, Fix Code

#112 Fix Code Excel in Brand Material
  src/main/java/com/smart/tailor/service/impl/BrandMaterialServiceImpl.java
  src/main/java/com/smart/tailor/service/impl/MaterialServiceImpl.java
  src/main/resources/application.properties
  src/main/resources/smartTailorScript.sql
Labels: function, update, Fix Code

#115 Add Index to ListBrandMaterialRequest
  src/main/java/com/smart/tailor/service/impl/BrandMaterialServiceImpl.java
  src/main/resources/smartTailorScript.sql
Labels: function, update

#116 [BE0038] payment feature
  pom.xml
  src/main/java/com/smart/tailor/constant/APIConstant.java
  src/main/java/com/smart/tailor/constant/MessageConstant.java
  src/main/java/com/smart/tailor/controller/PaymentController.java
  src/main/java/com/smart/tailor/entities/Payment.java
  src/main/java/com/smart/tailor/entities/User.java
  src/main/java/com/smart/tailor/enums/PaymentType.java
  src/main/java/com/smart/tailor/mapper/PaymentMapper.java
  src/main/java/com/smart/tailor/repository/PaymentRepository.java
  src/main/java/com/smart/tailor/service/OrderService.java
  src/main/java/com/smart/tailor/service/PayOSService.java
  src/main/java/com/smart/tailor/service/PaymentService.java
  src/main/java/com/smart/tailor/service/impl/OrderServiceImpl.java
  src/main/java/com/smart/tailor/service/impl/PayOSServiceImpl.java
  src/main/java/com/smart/tailor/service/impl/PaymentServiceImpl.java
  src/main/java/com/smart/tailor/utils/request/PayOSItem.java
  src/main/java/com/smart/tailor/utils/request/PayOSRequest.java
  src/main/java/com/smart/tailor/utils/request/PaymentRequest.java
  src/main/java/com/smart/tailor/utils/response/PayOSResponse.java
  src/main/java/com/smart/tailor/utils/response/PayOSResponseData.java
  src/main/java/com/smart/tailor/utils/response/PaymentResponse.java
  src/main/resources/application.properties
  src/main/resources/smartTailorScript.sql
Labels: function, Fix Code

#120 [BE0038] create payment
  src/main/java/com/smart/tailor/entities/Design.java
  src/main/java/com/smart/tailor/entities/DesignDetail.java
  src/main/java/com/smart/tailor/entities/Order.java
  src/main/java/com/smart/tailor/entities/Payment.java
  src/main/java/com/smart/tailor/mapper/DesignDetailMapper.java
  src/main/java/com/smart/tailor/mapper/OrderMapper.java
  src/main/java/com/smart/tailor/mapper/PaymentMapper.java
  src/main/java/com/smart/tailor/repository/BrandMaterialRepository.java
  src/main/java/com/smart/tailor/repository/PaymentRepository.java
  src/main/java/com/smart/tailor/service/BrandMaterialService.java
  src/main/java/com/smart/tailor/service/OrderService.java
  src/main/java/com/smart/tailor/service/ScheduleTaskService.java
  src/main/java/com/smart/tailor/service/impl/BrandMaterialServiceImpl.java
  src/main/java/com/smart/tailor/service/impl/DesignDetailServiceImpl.java
  src/main/java/com/smart/tailor/service/impl/DesignServiceImpl.java
  src/main/java/com/smart/tailor/service/impl/OrderServiceImpl.java
  src/main/java/com/smart/tailor/service/impl/PartOfDesignServiceImpl.java
  src/main/java/com/smart/tailor/service/impl/PayOSServiceImpl.java
  src/main/java/com/smart/tailor/service/impl/PaymentServiceImpl.java
  src/main/java/com/smart/tailor/service/impl/ScheduleTaskServiceImpl.java
  src/main/java/com/smart/tailor/utils/response/DesignMaterialDetail.java
  src/main/java/com/smart/tailor/utils/response/OrderCustomResponse.java
  src/main/java/com/smart/tailor/utils/response/OrderResponse.java
  src/main/resources/application.properties
Labels: bug, function, Fix Code

#121 [BE0038] Payment Feature
  src/main/java/com/smart/tailor/entities/PayOSData.java
  src/main/java/com/smart/tailor/entities/Payment.java
  src/main/java/com/smart/tailor/mapper/OrderMapper.java
  src/main/java/com/smart/tailor/mapper/PayOSDataMapper.java
  src/main/java/com/smart/tailor/mapper/PaymentMapper.java
  src/main/java/com/smart/tailor/repository/PayOSDataRepository.java
  src/main/java/com/smart/tailor/service/OrderService.java
  src/main/java/com/smart/tailor/service/PayOSService.java
  src/main/java/com/smart/tailor/service/impl/DesignDetailServiceImpl.java
  src/main/java/com/smart/tailor/service/impl/OrderServiceImpl.java
  src/main/java/com/smart/tailor/service/impl/PayOSServiceImpl.java
  src/main/java/com/smart/tailor/service/impl/PaymentServiceImpl.java
  src/main/java/com/smart/tailor/utils/Utilities.java
  src/main/resources/smartTailorScript.sql
Labels: bug, function, update, Fix Code

#122 Update Response in Material and BrandMaterial
  src/main/java/com/smart/tailor/service/impl/BrandMaterialServiceImpl.java
  src/main/java/com/smart/tailor/service/impl/MaterialServiceImpl.java
  src/main/resources/application.properties
Labels: function, update, Fix Code

#124 [BE0038] update payment feature
  src/main/java/com/smart/tailor/enums/PaymentType.java
  src/main/java/com/smart/tailor/mapper/OrderMapper.java
  src/main/java/com/smart/tailor/mapper/PaymentMapper.java
  src/main/java/com/smart/tailor/service/PaymentService.java
  src/main/java/com/smart/tailor/service/impl/OrderServiceImpl.java
  src/main/java/com/smart/tailor/service/impl/PaymentServiceImpl.java
  src/main/java/com/smart/tailor/utils/response/OrderCustomResponse.java
  src/main/java/com/smart/tailor/utils/response/PaymentResponse.java
  src/main/resources/smartTailorScript.sql
Labels: update, Fix Code

#127 Calculate BrandLaborQuantity for Each Order
  src/main/java/com/smart/tailor/repository/BrandLaborQuantityRepository.java
  src/main/java/com/smart/tailor/service/BrandLaborQuantityService.java
  src/main/java/com/smart/tailor/service/impl/BrandLaborQuantityServiceImpl.java
  src/main/java/com/smart/tailor/service/impl/DesignDetailServiceImpl.java
Labels: function

#128 [BE0038] fix payment feature
  src/main/java/com/smart/tailor/controller/PaymentController.java
  src/main/java/com/smart/tailor/entities/Order.java
  src/main/java/com/smart/tailor/entities/PayOSData.java
  src/main/java/com/smart/tailor/entities/Payment.java
  src/main/java/com/smart/tailor/mapper/OrderMapper.java
  src/main/java/com/smart/tailor/mapper/PayOSDataMapper.java
  src/main/java/com/smart/tailor/mapper/PaymentMapper.java
  src/main/java/com/smart/tailor/repository/PayOSDataRepository.java
  src/main/java/com/smart/tailor/repository/PaymentRepository.java
  src/main/java/com/smart/tailor/service/PayOSDataService.java
  src/main/java/com/smart/tailor/service/PayOSService.java
  src/main/java/com/smart/tailor/service/PaymentService.java
  src/main/java/com/smart/tailor/service/impl/DesignServiceImpl.java
  src/main/java/com/smart/tailor/service/impl/OrderServiceImpl.java
  src/main/java/com/smart/tailor/service/impl/PayOSDataServiceImpl.java
  src/main/java/com/smart/tailor/service/impl/PayOSServiceImpl.java
  src/main/java/com/smart/tailor/service/impl/PaymentServiceImpl.java
  src/main/java/com/smart/tailor/service/impl/ScheduleTaskServiceImpl.java
  src/main/java/com/smart/tailor/utils/request/PaymentRequest.java
  src/main/java/com/smart/tailor/utils/response/PayOSCreationResponse.java
  src/main/java/com/smart/tailor/utils/response/PayOSCreationResponseData.java
  src/main/java/com/smart/tailor/utils/response/PayOSResponseData.java
  src/main/java/com/smart/tailor/utils/response/Transactions.java
  src/main/resources/application.properties
Labels: bug, update, Fix Code

#129 [BE0059] Add Constraint to Fields in DB
  src/main/java/com/smart/tailor/entities/AuditEntity.java
  src/main/java/com/smart/tailor/entities/Brand.java
  src/main/java/com/smart/tailor/entities/BrandLaborQuantity.java
  src/main/java/com/smart/tailor/entities/BrandProperties.java
  src/main/java/com/smart/tailor/entities/Category.java
  src/main/java/com/smart/tailor/entities/Customer.java
  src/main/java/com/smart/tailor/entities/Design.java
  src/main/java/com/smart/tailor/entities/ExpertTailoring.java
  src/main/java/com/smart/tailor/entities/ItemMask.java
  src/main/java/com/smart/tailor/entities/LaborQuantity.java
  src/main/java/com/smart/tailor/entities/Material.java
  src/main/java/com/smart/tailor/entities/Notification.java
  src/main/java/com/smart/tailor/entities/Order.java
  src/main/java/com/smart/tailor/entities/PartOfDesign.java
  src/main/java/com/smart/tailor/entities/PayOSData.java
  src/main/java/com/smart/tailor/entities/Payment.java
  src/main/java/com/smart/tailor/entities/Report.java
  src/main/java/com/smart/tailor/entities/ReportImage.java
  src/main/java/com/smart/tailor/entities/Roles.java
  src/main/java/com/smart/tailor/entities/Size.java
  src/main/java/com/smart/tailor/entities/SizeExpertTailoring.java
  src/main/java/com/smart/tailor/entities/SystemImage.java
  src/main/java/com/smart/tailor/entities/SystemProperties.java
  src/main/java/com/smart/tailor/entities/Task.java
  src/main/java/com/smart/tailor/entities/User.java
  src/main/java/com/smart/tailor/service/impl/LaborQuantityServiceImpl.java
  src/main/java/com/smart/tailor/utils/request/BrandLaborQuantityRequest.java
  src/main/java/com/smart/tailor/utils/request/LaborQuantityRequest.java
  src/main/resources/application.properties
Labels: function, update

#131 Update ItemMask Entity and Design
  src/main/java/com/smart/tailor/entities/ItemMask.java
  src/main/java/com/smart/tailor/enums/PrintType.java
  src/main/java/com/smart/tailor/mapper/ItemMaskMapper.java
  src/main/java/com/smart/tailor/service/impl/ItemMaskServiceImpl.java
  src/main/java/com/smart/tailor/utils/request/ItemMaskRequest.java
  src/main/java/com/smart/tailor/utils/response/ItemMaskResponse.java
Labels: function, update

#132 Update Code Related to Constraint Fields in DB version 1.0
  src/main/java/com/smart/tailor/controller/BrandPropertyController.java
  src/main/java/com/smart/tailor/controller/CustomerController.java
  src/main/java/com/smart/tailor/controller/SystemImageController.java
  src/main/java/com/smart/tailor/controller/SystemPropertyController.java
  src/main/java/com/smart/tailor/entities/BrandProperties.java
  src/main/java/com/smart/tailor/entities/SystemProperties.java
  src/main/java/com/smart/tailor/service/SizeServiceImpl.java
  src/main/java/com/smart/tailor/service/impl/BrandMaterialServiceImpl.java
  src/main/java/com/smart/tailor/service/impl/BrandPropertiesServiceImpl.java
  src/main/java/com/smart/tailor/service/impl/CategoryServiceImpl.java
  src/main/java/com/smart/tailor/service/impl/ExpertTailoringServiceImpl.java
  src/main/java/com/smart/tailor/service/impl/ItemMaskServiceImpl.java
  src/main/java/com/smart/tailor/service/impl/MaterialServiceImpl.java
  src/main/java/com/smart/tailor/service/impl/SystemImageServiceImpl.java
  src/main/java/com/smart/tailor/service/impl/SystemPropertiesServiceImpl.java
  src/main/java/com/smart/tailor/utils/request/BrandMaterialRequest.java
  src/main/java/com/smart/tailor/utils/request/BrandPropertiesRequest.java
  src/main/java/com/smart/tailor/utils/request/CategoryListRequest.java
  src/main/java/com/smart/tailor/utils/request/CategoryRequest.java
  src/main/java/com/smart/tailor/utils/request/CustomerRequest.java
  src/main/java/com/smart/tailor/utils/request/DesignRequest.java
  src/main/java/com/smart/tailor/utils/request/ExpertTailoringRequest.java
  src/main/java/com/smart/tailor/utils/request/ItemMaskRequest.java
  src/main/java/com/smart/tailor/utils/request/ListSizeRequest.java
  src/main/java/com/smart/tailor/utils/request/MaterialRequest.java
  src/main/java/com/smart/tailor/utils/request/PartOfDesignRequest.java
  src/main/java/com/smart/tailor/utils/request/SizeRequest.java
  src/main/java/com/smart/tailor/utils/request/SystemImageRequest.java
  src/main/java/com/smart/tailor/utils/request/SystemPropertiesRequest.java
  src/main/java/com/smart/tailor/utils/request/UserRequest.java
  src/main/java/com/smart/tailor/validate/ValidColor.java
  src/main/java/com/smart/tailor/validate/ValidColorConstraint.java
Labels: function, update, Fix Code

#133 Create Report, Report Image and Update ItemMask
  src/main/java/com/smart/tailor/constant/APIConstant.java
  src/main/java/com/smart/tailor/constant/MessageConstant.java
  src/main/java/com/smart/tailor/controller/ReportController.java
  src/main/java/com/smart/tailor/entities/ItemMask.java
  src/main/java/com/smart/tailor/entities/Report.java
  src/main/java/com/smart/tailor/entities/ReportImage.java
  src/main/java/com/smart/tailor/mapper/ItemMaskMapper.java
  src/main/java/com/smart/tailor/mapper/ReportImageMapper.java
  src/main/java/com/smart/tailor/mapper/ReportMapper.java
  src/main/java/com/smart/tailor/repository/ReportImageRepository.java
  src/main/java/com/smart/tailor/service/ReportImageService.java
  src/main/java/com/smart/tailor/service/ReportService.java
  src/main/java/com/smart/tailor/service/impl/ItemMaskServiceImpl.java
  src/main/java/com/smart/tailor/service/impl/ReportImageServiceImpl.java
  src/main/java/com/smart/tailor/service/impl/ReportServiceImpl.java
  src/main/java/com/smart/tailor/utils/request/ItemMaskRequest.java
  src/main/java/com/smart/tailor/utils/request/ReportImageRequest.java
  src/main/java/com/smart/tailor/utils/request/ReportRequest.java
  src/main/java/com/smart/tailor/utils/response/ItemMaskResponse.java
  src/main/java/com/smart/tailor/utils/response/ReportImageResponse.java
  src/main/java/com/smart/tailor/utils/response/ReportResponse.java
  src/main/resources/application.properties
Labels: function, update, Fix Code

#134 [BE0038] update confirm payment
  src/main/java/com/smart/tailor/service/impl/DesignDetailServiceImpl.java
  src/main/java/com/smart/tailor/service/impl/OrderServiceImpl.java
  src/main/java/com/smart/tailor/service/impl/PayOSServiceImpl.java
  src/main/java/com/smart/tailor/service/impl/PaymentServiceImpl.java
  src/main/java/com/smart/tailor/service/impl/ScheduleTaskServiceImpl.java
  src/main/resources/application.properties
Labels: update, Fix Code

#135 [BE0038] fix bug stackOverFlow
  src/main/java/com/smart/tailor/entities/Order.java
  src/main/java/com/smart/tailor/service/impl/DesignDetailServiceImpl.java
  src/main/java/com/smart/tailor/service/impl/OrderServiceImpl.java
Labels: bug, update, Fix Code

#137 Update PAYOS
  src/main/java/com/smart/tailor/entities/Order.java
  src/main/java/com/smart/tailor/entities/Payment.java
  src/main/java/com/smart/tailor/service/impl/OrderServiceImpl.java
  src/main/java/com/smart/tailor/service/impl/ScheduleTaskServiceImpl.java
Labels: update, Fix Code

#136 [BE0062] Create Authentication and Authorization
  src/main/java/com/smart/tailor/config/RestAccessDenyEntryPoint.java
  src/main/java/com/smart/tailor/config/RestUnauthorizedEntryPoint.java
  src/main/java/com/smart/tailor/config/SecurityConfig.java
  src/main/java/com/smart/tailor/constant/APIConstant.java
  src/main/java/com/smart/tailor/constant/MessageConstant.java
  src/main/java/com/smart/tailor/controller/UserController.java
  src/main/resources/smartTailorScript.sql
Labels: function

#138 Update MinWeight and MaxWeight to Design
  src/main/java/com/smart/tailor/config/SecurityConfig.java
  src/main/java/com/smart/tailor/controller/DesignDetailController.java
  src/main/java/com/smart/tailor/entities/Design.java
  src/main/java/com/smart/tailor/event/CreateDesignDetailEvent.java
  src/main/java/com/smart/tailor/event/listener/CreateDesignDetailEventListener.java
  src/main/java/com/smart/tailor/mapper/DesignMapper.java
  src/main/java/com/smart/tailor/service/impl/DesignServiceImpl.java
  src/main/java/com/smart/tailor/service/impl/OrderServiceImpl.java
  src/main/java/com/smart/tailor/service/impl/ScheduleTaskServiceImpl.java
  src/main/java/com/smart/tailor/utils/request/DesignRequest.java
  src/main/java/com/smart/tailor/utils/request/OrderStatusUpdateRequest.java
  src/main/java/com/smart/tailor/utils/response/DesignCustomResponse.java
  src/main/java/com/smart/tailor/utils/response/DesignResponse.java
Labels: function, update, Fix Code

#139 [BE0067] order fullfillment process
  src/main/java/com/smart/tailor/enums/OrderStatus.java
  src/main/java/com/smart/tailor/service/impl/OrderServiceImpl.java
Labels: function

#140 Update and Fix Code Send Mail to Order
  src/main/java/com/smart/tailor/controller/OrderController.java
  src/main/java/com/smart/tailor/event/CreateOrderEvent.java
  src/main/java/com/smart/tailor/event/listener/CreateOrderEventListener.java
  src/main/java/com/smart/tailor/service/impl/OrderServiceImpl.java
Labels: function, update, Fix Code

#141 [BE0067] update system type when run schedule
  src/main/java/com/smart/tailor/repository/SystemPropertiesRepository.java
  src/main/java/com/smart/tailor/service/SystemPropertiesService.java
  src/main/java/com/smart/tailor/service/impl/OrderServiceImpl.java
  src/main/java/com/smart/tailor/service/impl/SystemPropertiesServiceImpl.java
Labels: function, update

#142 [BE0032] update get order by brandID and userID
  src/main/java/com/smart/tailor/constant/APIConstant.java
  src/main/java/com/smart/tailor/controller/OrderController.java
  src/main/java/com/smart/tailor/repository/OrderRepository.java
  src/main/java/com/smart/tailor/service/OrderService.java
  src/main/java/com/smart/tailor/service/impl/OrderServiceImpl.java
Labels: function, update

#143 [BE0032] update get order by brandID
  src/main/java/com/smart/tailor/repository/OrderRepository.java
  src/main/java/com/smart/tailor/service/OrderService.java
  src/main/java/com/smart/tailor/service/impl/OrderServiceImpl.java
Labels: function, update

#144 [BE0032] update manual payment for order flow
  src/main/java/com/smart/tailor/config/VNPayConfig.java
  src/main/java/com/smart/tailor/constant/APIConstant.java
  src/main/java/com/smart/tailor/constant/MessageConstant.java
  src/main/java/com/smart/tailor/controller/PaymentController.java
  src/main/java/com/smart/tailor/entities/Payment.java
  src/main/java/com/smart/tailor/enums/PaymentType.java
  src/main/java/com/smart/tailor/mapper/PaymentMapper.java
  src/main/java/com/smart/tailor/service/PaymentService.java
  src/main/java/com/smart/tailor/service/impl/PayOSServiceImpl.java
  src/main/java/com/smart/tailor/service/impl/PaymentServiceImpl.java
  src/main/java/com/smart/tailor/utils/response/PaymentResponse.java
  src/main/java/com/smart/tailor/utils/response/VNPAYResponse.java
  src/main/resources/application.properties
Labels: function, update, Fix Code

#145 Update Validation with UUID and GetAllReportBy User and Brand
  src/main/java/com/smart/tailor/config/SecurityConfig.java
  src/main/java/com/smart/tailor/constant/APIConstant.java
  src/main/java/com/smart/tailor/constant/MessageConstant.java
  src/main/java/com/smart/tailor/controller/OrderController.java
  src/main/java/com/smart/tailor/controller/PaymentController.java
  src/main/java/com/smart/tailor/controller/ReportController.java
  src/main/java/com/smart/tailor/repository/ReportRepository.java
  src/main/java/com/smart/tailor/service/ReportService.java
  src/main/java/com/smart/tailor/service/impl/ReportServiceImpl.java
Labels: function, update, Fix Code

#147 [BE0067] order fullfillment process
  src/main/java/com/smart/tailor/mapper/OrderMapper.java
  src/main/java/com/smart/tailor/repository/BrandPropertiesRepository.java
  src/main/java/com/smart/tailor/service/BrandPropertiesService.java
  src/main/java/com/smart/tailor/service/OrderService.java
  src/main/java/com/smart/tailor/service/impl/BrandPropertiesServiceImpl.java
  src/main/java/com/smart/tailor/service/impl/OrderServiceImpl.java
  src/main/java/com/smart/tailor/service/impl/PaymentServiceImpl.java
  src/main/java/com/smart/tailor/service/impl/ScheduleTaskServiceImpl.java
  src/main/java/com/smart/tailor/utils/Utilities.java
  src/main/java/com/smart/tailor/utils/response/OrderCustomResponse.java
  src/main/java/com/smart/tailor/utils/response/OrderResponse.java
  src/main/resources/smartTailorScript.sql
Labels: function, update

#148 Feature be0067 order fullfillment process
  src/main/java/com/smart/tailor/constant/APIConstant.java
  src/main/java/com/smart/tailor/constant/MessageConstant.java
  src/main/java/com/smart/tailor/controller/SampleProductDataController.java
  src/main/java/com/smart/tailor/entities/SampleProductData.java
  src/main/java/com/smart/tailor/enums/OrderStatus.java
  src/main/java/com/smart/tailor/repository/SampleProductDataRepository.java
  src/main/java/com/smart/tailor/service/EmployeeService.java
  src/main/java/com/smart/tailor/service/SampleProductDataService.java
  src/main/java/com/smart/tailor/service/impl/EmployeeServiceImpl.java
  src/main/java/com/smart/tailor/service/impl/OrderServiceImpl.java
  src/main/java/com/smart/tailor/service/impl/SampleProductDataServiceImpl.java
  src/main/java/com/smart/tailor/utils/request/SampleProductDataRequest.java
Labels: function

#149 [BE0067] fix enpoint error
  src/main/java/com/smart/tailor/constant/APIConstant.java
Labels: bug, update, Fix Code

#150 [BE0067] upload get sample by orderID
  src/main/java/com/smart/tailor/constant/APIConstant.java
  src/main/java/com/smart/tailor/controller/SampleProductDataController.java
  src/main/java/com/smart/tailor/repository/SampleProductDataRepository.java
  src/main/java/com/smart/tailor/service/SampleProductDataService.java
  src/main/java/com/smart/tailor/service/impl/SampleProductDataServiceImpl.java
Labels: function, update

#151 Update Code SamppleProductData
  src/main/java/com/smart/tailor/constant/APIConstant.java
  src/main/java/com/smart/tailor/constant/MessageConstant.java
  src/main/java/com/smart/tailor/controller/SampleProductDataController.java
  src/main/java/com/smart/tailor/entities/SampleProductData.java
  src/main/java/com/smart/tailor/mapper/SampleProductDataMapper.java
  src/main/java/com/smart/tailor/repository/SampleProductDataRepository.java
  src/main/java/com/smart/tailor/service/SampleProductDataService.java
  src/main/java/com/smart/tailor/service/impl/ExpertTailoringMaterialServiceImpl.java
  src/main/java/com/smart/tailor/service/impl/PartOfDesignServiceImpl.java
  src/main/java/com/smart/tailor/service/impl/SampleProductDataServiceImpl.java
  src/main/java/com/smart/tailor/utils/request/SampleProductDataRequest.java
  src/main/java/com/smart/tailor/utils/response/SampleProductDataResponse.java
Labels: function, update, Fix Code

#152 Update Code SampleProductData about ParentOrder and SubOrder
  src/main/java/com/smart/tailor/constant/APIConstant.java
  src/main/java/com/smart/tailor/controller/SampleProductDataController.java
  src/main/java/com/smart/tailor/service/SampleProductDataService.java
  src/main/java/com/smart/tailor/service/impl/SampleProductDataServiceImpl.java
  src/main/java/com/smart/tailor/utils/request/SampleProductDataRequest.java
Labels: update, Fix Code
